function [Time,Speed1,Speed2,Speed3,Temp] = importWindDataFcn(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME,SPEED1,SPEED2,SPEED3,TEMP] = IMPORTFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   [TIME,SPEED1,SPEED2,SPEED3,TEMP] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [Time,Speed1,Speed2,Speed3,Temp] = importfile('winddata.txt',2, 8777);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/06/05 16:17:39

% Copyright 2013-2016 The MathWorks, Inc.

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: datetimes (%{dd-MMM-yyyy HH:mm}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{dd-MMM-yyyy HH:mm}D%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
Speed1 = dataArray{:, 2};
Speed2 = dataArray{:, 3};
Speed3 = dataArray{:, 4};
Temp = dataArray{:, 5};


