%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\rqian\Desktop\ProgrammingWithMATLAB\winddata.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/05/03 10:08:44

% Copyright 2013-2016 The MathWorks, Inc.

%% Initialize variables.
filename = 'C:\Users\rqian\Desktop\ProgrammingWithMATLAB\winddata.txt';
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: datetimes (%{dd-MMM-yyyy HH:mm}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{dd-MMM-yyyy HH:mm}D%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
Speed1 = dataArray{:, 2};
Speed2 = dataArray{:, 3};
Speed3 = dataArray{:, 4};
Temp = dataArray{:, 5};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% Time=datenum(Time);


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;